name: Deploy Package to NPM when a Release is Created
on:
  release:
    types: [created]
jobs:
  publish:
    name: Publish release to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install latest npm
        run: npm install -g npm@latest
      - name: Build package
        run: |
          yarn install
          yarn build
      - name: Publish package NPM
        run: npm publish --access public
